apiVersion: v1
kind: Service
metadata:
  name: symfony
  labels:
    app: symfony
  namespace: default
spec:
  type: NodePort
  selector:
    app: symfony
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
